name: Daily Auto Commit

on:
  schedule:
    - cron: "25 16 * * *"
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 21f3003074@ds.study.iitm.ac.in Auto Commit Step
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "21f3003074@ds.study.iitm.ac.in"

          echo "Last updated on $(date)" >> daily-log.txt
          git add daily-log.txt
          git commit -m "Daily automated commit" || echo "No changes"
          git push
